// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: addr.proto

#ifndef PROTOBUF_addr_2eproto__INCLUDED
#define PROTOBUF_addr_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_addr_2eproto();
void protobuf_AssignDesc_addr_2eproto();
void protobuf_ShutdownFile_addr_2eproto();

class Persion;
class Persion_PhoneNumber;

enum Persion_PhoneType {
  Persion_PhoneType_MOBILE = 0,
  Persion_PhoneType_HOME = 1,
  Persion_PhoneType_WORK = 2
};
bool Persion_PhoneType_IsValid(int value);
const Persion_PhoneType Persion_PhoneType_PhoneType_MIN = Persion_PhoneType_MOBILE;
const Persion_PhoneType Persion_PhoneType_PhoneType_MAX = Persion_PhoneType_WORK;
const int Persion_PhoneType_PhoneType_ARRAYSIZE = Persion_PhoneType_PhoneType_MAX + 1;

const ::google::protobuf::EnumDescriptor* Persion_PhoneType_descriptor();
inline const ::std::string& Persion_PhoneType_Name(Persion_PhoneType value) {
  return ::google::protobuf::internal::NameOfEnum(
    Persion_PhoneType_descriptor(), value);
}
inline bool Persion_PhoneType_Parse(
    const ::std::string& name, Persion_PhoneType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<Persion_PhoneType>(
    Persion_PhoneType_descriptor(), name, value);
}
// ===================================================================

class Persion_PhoneNumber : public ::google::protobuf::Message {
 public:
  Persion_PhoneNumber();
  virtual ~Persion_PhoneNumber();

  Persion_PhoneNumber(const Persion_PhoneNumber& from);

  inline Persion_PhoneNumber& operator=(const Persion_PhoneNumber& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Persion_PhoneNumber& default_instance();

  void Swap(Persion_PhoneNumber* other);

  // implements Message ----------------------------------------------

  Persion_PhoneNumber* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Persion_PhoneNumber& from);
  void MergeFrom(const Persion_PhoneNumber& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string phoneNum = 1;
  inline bool has_phonenum() const;
  inline void clear_phonenum();
  static const int kPhoneNumFieldNumber = 1;
  inline const ::std::string& phonenum() const;
  inline void set_phonenum(const ::std::string& value);
  inline void set_phonenum(const char* value);
  inline void set_phonenum(const char* value, size_t size);
  inline ::std::string* mutable_phonenum();
  inline ::std::string* release_phonenum();
  inline void set_allocated_phonenum(::std::string* phonenum);

  // optional .Persion.PhoneType type = 2 [default = HOME];
  inline bool has_type() const;
  inline void clear_type();
  static const int kTypeFieldNumber = 2;
  inline ::Persion_PhoneType type() const;
  inline void set_type(::Persion_PhoneType value);

  // @@protoc_insertion_point(class_scope:Persion.PhoneNumber)
 private:
  inline void set_has_phonenum();
  inline void clear_has_phonenum();
  inline void set_has_type();
  inline void clear_has_type();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::std::string* phonenum_;
  int type_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_addr_2eproto();
  friend void protobuf_AssignDesc_addr_2eproto();
  friend void protobuf_ShutdownFile_addr_2eproto();

  void InitAsDefaultInstance();
  static Persion_PhoneNumber* default_instance_;
};
// -------------------------------------------------------------------

class Persion : public ::google::protobuf::Message {
 public:
  Persion();
  virtual ~Persion();

  Persion(const Persion& from);

  inline Persion& operator=(const Persion& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Persion& default_instance();

  void Swap(Persion* other);

  // implements Message ----------------------------------------------

  Persion* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Persion& from);
  void MergeFrom(const Persion& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef Persion_PhoneNumber PhoneNumber;

  typedef Persion_PhoneType PhoneType;
  static const PhoneType MOBILE = Persion_PhoneType_MOBILE;
  static const PhoneType HOME = Persion_PhoneType_HOME;
  static const PhoneType WORK = Persion_PhoneType_WORK;
  static inline bool PhoneType_IsValid(int value) {
    return Persion_PhoneType_IsValid(value);
  }
  static const PhoneType PhoneType_MIN =
    Persion_PhoneType_PhoneType_MIN;
  static const PhoneType PhoneType_MAX =
    Persion_PhoneType_PhoneType_MAX;
  static const int PhoneType_ARRAYSIZE =
    Persion_PhoneType_PhoneType_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  PhoneType_descriptor() {
    return Persion_PhoneType_descriptor();
  }
  static inline const ::std::string& PhoneType_Name(PhoneType value) {
    return Persion_PhoneType_Name(value);
  }
  static inline bool PhoneType_Parse(const ::std::string& name,
      PhoneType* value) {
    return Persion_PhoneType_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // required string name = 1;
  inline bool has_name() const;
  inline void clear_name();
  static const int kNameFieldNumber = 1;
  inline const ::std::string& name() const;
  inline void set_name(const ::std::string& value);
  inline void set_name(const char* value);
  inline void set_name(const char* value, size_t size);
  inline ::std::string* mutable_name();
  inline ::std::string* release_name();
  inline void set_allocated_name(::std::string* name);

  // required int32 id = 2;
  inline bool has_id() const;
  inline void clear_id();
  static const int kIdFieldNumber = 2;
  inline ::google::protobuf::int32 id() const;
  inline void set_id(::google::protobuf::int32 value);

  // optional string email = 3;
  inline bool has_email() const;
  inline void clear_email();
  static const int kEmailFieldNumber = 3;
  inline const ::std::string& email() const;
  inline void set_email(const ::std::string& value);
  inline void set_email(const char* value);
  inline void set_email(const char* value, size_t size);
  inline ::std::string* mutable_email();
  inline ::std::string* release_email();
  inline void set_allocated_email(::std::string* email);

  // repeated .Persion.PhoneNumber phone = 4;
  inline int phone_size() const;
  inline void clear_phone();
  static const int kPhoneFieldNumber = 4;
  inline const ::Persion_PhoneNumber& phone(int index) const;
  inline ::Persion_PhoneNumber* mutable_phone(int index);
  inline ::Persion_PhoneNumber* add_phone();
  inline const ::google::protobuf::RepeatedPtrField< ::Persion_PhoneNumber >&
      phone() const;
  inline ::google::protobuf::RepeatedPtrField< ::Persion_PhoneNumber >*
      mutable_phone();

  // @@protoc_insertion_point(class_scope:Persion)
 private:
  inline void set_has_name();
  inline void clear_has_name();
  inline void set_has_id();
  inline void clear_has_id();
  inline void set_has_email();
  inline void clear_has_email();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::std::string* name_;
  ::std::string* email_;
  ::google::protobuf::RepeatedPtrField< ::Persion_PhoneNumber > phone_;
  ::google::protobuf::int32 id_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(4 + 31) / 32];

  friend void  protobuf_AddDesc_addr_2eproto();
  friend void protobuf_AssignDesc_addr_2eproto();
  friend void protobuf_ShutdownFile_addr_2eproto();

  void InitAsDefaultInstance();
  static Persion* default_instance_;
};
// ===================================================================


// ===================================================================

// Persion_PhoneNumber

// required string phoneNum = 1;
inline bool Persion_PhoneNumber::has_phonenum() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Persion_PhoneNumber::set_has_phonenum() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Persion_PhoneNumber::clear_has_phonenum() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Persion_PhoneNumber::clear_phonenum() {
  if (phonenum_ != &::google::protobuf::internal::kEmptyString) {
    phonenum_->clear();
  }
  clear_has_phonenum();
}
inline const ::std::string& Persion_PhoneNumber::phonenum() const {
  return *phonenum_;
}
inline void Persion_PhoneNumber::set_phonenum(const ::std::string& value) {
  set_has_phonenum();
  if (phonenum_ == &::google::protobuf::internal::kEmptyString) {
    phonenum_ = new ::std::string;
  }
  phonenum_->assign(value);
}
inline void Persion_PhoneNumber::set_phonenum(const char* value) {
  set_has_phonenum();
  if (phonenum_ == &::google::protobuf::internal::kEmptyString) {
    phonenum_ = new ::std::string;
  }
  phonenum_->assign(value);
}
inline void Persion_PhoneNumber::set_phonenum(const char* value, size_t size) {
  set_has_phonenum();
  if (phonenum_ == &::google::protobuf::internal::kEmptyString) {
    phonenum_ = new ::std::string;
  }
  phonenum_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* Persion_PhoneNumber::mutable_phonenum() {
  set_has_phonenum();
  if (phonenum_ == &::google::protobuf::internal::kEmptyString) {
    phonenum_ = new ::std::string;
  }
  return phonenum_;
}
inline ::std::string* Persion_PhoneNumber::release_phonenum() {
  clear_has_phonenum();
  if (phonenum_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = phonenum_;
    phonenum_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void Persion_PhoneNumber::set_allocated_phonenum(::std::string* phonenum) {
  if (phonenum_ != &::google::protobuf::internal::kEmptyString) {
    delete phonenum_;
  }
  if (phonenum) {
    set_has_phonenum();
    phonenum_ = phonenum;
  } else {
    clear_has_phonenum();
    phonenum_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// optional .Persion.PhoneType type = 2 [default = HOME];
inline bool Persion_PhoneNumber::has_type() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Persion_PhoneNumber::set_has_type() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Persion_PhoneNumber::clear_has_type() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Persion_PhoneNumber::clear_type() {
  type_ = 1;
  clear_has_type();
}
inline ::Persion_PhoneType Persion_PhoneNumber::type() const {
  return static_cast< ::Persion_PhoneType >(type_);
}
inline void Persion_PhoneNumber::set_type(::Persion_PhoneType value) {
  assert(::Persion_PhoneType_IsValid(value));
  set_has_type();
  type_ = value;
}

// -------------------------------------------------------------------

// Persion

// required string name = 1;
inline bool Persion::has_name() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Persion::set_has_name() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Persion::clear_has_name() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Persion::clear_name() {
  if (name_ != &::google::protobuf::internal::kEmptyString) {
    name_->clear();
  }
  clear_has_name();
}
inline const ::std::string& Persion::name() const {
  return *name_;
}
inline void Persion::set_name(const ::std::string& value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  name_->assign(value);
}
inline void Persion::set_name(const char* value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  name_->assign(value);
}
inline void Persion::set_name(const char* value, size_t size) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  name_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* Persion::mutable_name() {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  return name_;
}
inline ::std::string* Persion::release_name() {
  clear_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = name_;
    name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void Persion::set_allocated_name(::std::string* name) {
  if (name_ != &::google::protobuf::internal::kEmptyString) {
    delete name_;
  }
  if (name) {
    set_has_name();
    name_ = name;
  } else {
    clear_has_name();
    name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// required int32 id = 2;
inline bool Persion::has_id() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Persion::set_has_id() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Persion::clear_has_id() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Persion::clear_id() {
  id_ = 0;
  clear_has_id();
}
inline ::google::protobuf::int32 Persion::id() const {
  return id_;
}
inline void Persion::set_id(::google::protobuf::int32 value) {
  set_has_id();
  id_ = value;
}

// optional string email = 3;
inline bool Persion::has_email() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Persion::set_has_email() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Persion::clear_has_email() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Persion::clear_email() {
  if (email_ != &::google::protobuf::internal::kEmptyString) {
    email_->clear();
  }
  clear_has_email();
}
inline const ::std::string& Persion::email() const {
  return *email_;
}
inline void Persion::set_email(const ::std::string& value) {
  set_has_email();
  if (email_ == &::google::protobuf::internal::kEmptyString) {
    email_ = new ::std::string;
  }
  email_->assign(value);
}
inline void Persion::set_email(const char* value) {
  set_has_email();
  if (email_ == &::google::protobuf::internal::kEmptyString) {
    email_ = new ::std::string;
  }
  email_->assign(value);
}
inline void Persion::set_email(const char* value, size_t size) {
  set_has_email();
  if (email_ == &::google::protobuf::internal::kEmptyString) {
    email_ = new ::std::string;
  }
  email_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* Persion::mutable_email() {
  set_has_email();
  if (email_ == &::google::protobuf::internal::kEmptyString) {
    email_ = new ::std::string;
  }
  return email_;
}
inline ::std::string* Persion::release_email() {
  clear_has_email();
  if (email_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = email_;
    email_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void Persion::set_allocated_email(::std::string* email) {
  if (email_ != &::google::protobuf::internal::kEmptyString) {
    delete email_;
  }
  if (email) {
    set_has_email();
    email_ = email;
  } else {
    clear_has_email();
    email_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// repeated .Persion.PhoneNumber phone = 4;
inline int Persion::phone_size() const {
  return phone_.size();
}
inline void Persion::clear_phone() {
  phone_.Clear();
}
inline const ::Persion_PhoneNumber& Persion::phone(int index) const {
  return phone_.Get(index);
}
inline ::Persion_PhoneNumber* Persion::mutable_phone(int index) {
  return phone_.Mutable(index);
}
inline ::Persion_PhoneNumber* Persion::add_phone() {
  return phone_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::Persion_PhoneNumber >&
Persion::phone() const {
  return phone_;
}
inline ::google::protobuf::RepeatedPtrField< ::Persion_PhoneNumber >*
Persion::mutable_phone() {
  return &phone_;
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {

template <>
inline const EnumDescriptor* GetEnumDescriptor< ::Persion_PhoneType>() {
  return ::Persion_PhoneType_descriptor();
}

}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_addr_2eproto__INCLUDED
